In [96]:
import torch
import numpy as np

## Create Tensor

In [7]:
#create empty tensor
x = torch.empty(2,2,2,3)
print(x)

tensor([[[[9.3663e+03, 3.0946e-41, 9.4642e+03],
          [3.0946e-41, 1.1210e-43, 0.0000e+00]],

         [[8.9683e-44, 0.0000e+00, 2.9033e-18],
          [3.0942e-41, 2.3592e-09, 2.0566e+20]]],


        [[[1.0413e-11, 2.6608e+23, 4.1912e+21],
          [3.3975e+21, 4.1292e-05, 2.1782e-04]],

         [[2.6539e+20, 2.4965e-18, 3.1360e+27],
          [7.0800e+31, 1.5835e-43, 0.0000e+00]]]])


In [8]:
#create random tensor
x = torch.rand(2,3)
print(x)

tensor([[0.0104, 0.8802, 0.4678],
        [0.2174, 0.7571, 0.9059]])


In [10]:
#create zeros tensor
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
#create ones tensor
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Format Tensor

In [15]:
#create ones tensor type float16
x = torch.ones(2,3, dtype=torch.float16)
print(x.size())
print(x)

torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)


### Tensor from List

In [18]:
#create tensor from list
x = torch.tensor([2.5, 0.5, 1,6])
print(x)

tensor([2.5000, 0.5000, 1.0000, 6.0000])


## Tensor Operations

In [65]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.2133, 0.1317],
        [0.7288, 0.7559]])
tensor([[0.3950, 0.2580],
        [0.2051, 0.1123]])


### Basic Operation

#### Addition

In [21]:
z=x+y
print(z)

tensor([[0.2062, 1.1467],
        [0.7921, 0.8485]])


In [23]:
z=torch.add(x,y)
print(z)

tensor([[0.2062, 1.1467],
        [0.7921, 0.8485]])


In [25]:
#inplace operation
y.add_(x)
print(y)

tensor([[0.2062, 1.1467],
        [0.7921, 0.8485]])


#### Substraction

In [43]:
z=x-y
print(z)

tensor([[-0.8970,  0.3422],
        [ 0.4633, -0.0871]])


In [44]:
z=torch.sub(x,y)
print(z)

tensor([[-0.8970,  0.3422],
        [ 0.4633, -0.0871]])


In [45]:
#inplace operation
y.sub_(x)
print(y)

tensor([[ 0.8970, -0.3422],
        [-0.4633,  0.0871]])


#### Multiplication

In [48]:
z=x*y
print(z)

tensor([[ 0.0603, -0.1224],
        [-0.4117,  0.0748]])


In [49]:
z=torch.mul(x,y)
print(z)

tensor([[ 0.0603, -0.1224],
        [-0.4117,  0.0748]])


In [ ]:
#inplace operation
y.mul_(x)
print(y)

#### Division

In [66]:
z=x/y
print(z)

tensor([[0.5400, 0.5103],
        [3.5526, 6.7318]])


In [67]:
z=torch.div(x,y)
print(z)

tensor([[0.5400, 0.5103],
        [3.5526, 6.7318]])


In [68]:
#inplace operation
x.div_(y)
print(x)

tensor([[0.5400, 0.5103],
        [3.5526, 6.7318]])


### Slicing Operations

In [71]:
# Create tensor of size 5 rows and 3 columns
x = torch.rand(5,3)
print(x)

tensor([[0.7935, 0.6249, 0.1172],
        [0.7466, 0.6820, 0.0960],
        [0.6641, 0.5674, 0.5701],
        [0.9879, 0.9817, 0.4279],
        [0.8838, 0.0663, 0.4582]])


In [72]:
#print all the rows for column 0 
print(x[:,0])

tensor([0.7935, 0.7466, 0.6641, 0.9879, 0.8838])


In [73]:
#print rows 1 and all the columns 
print(x[1,:])

tensor([0.7466, 0.6820, 0.0960])


In [76]:
#print rows 1 and columns 1 and get item
print(x[1,1].item())

0.6819540858268738


### Reshape tensor

In [77]:
x = torch.rand(4,4)
print(x)

tensor([[0.4494, 0.9517, 0.9207, 0.3164],
        [0.0796, 0.0120, 0.0408, 0.6348],
        [0.1070, 0.9884, 0.1501, 0.5489],
        [0.2524, 0.5345, 0.9216, 0.4694]])


In [78]:
y = x.view(16)
print(y)

tensor([0.4494, 0.9517, 0.9207, 0.3164, 0.0796, 0.0120, 0.0408, 0.6348, 0.1070,
        0.9884, 0.1501, 0.5489, 0.2524, 0.5345, 0.9216, 0.4694])


In [80]:
# reshape when i want to specify one dimention pytorch estimate the other dimention
y = x.view(-1,8)
print(y.size())

torch.Size([2, 8])


### Convert from numpy to tensor and viceversa

In [91]:
a = torch.ones(5)
print(a)
# from tensor to numpy array
b = a.numpy()
print(type(b))
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]


In [94]:
# Careful!
# if both a and b are in the same device, 
# both objects will share the same memory location
# both objects will be modified
a.add_(1)
print(a)
print(b)

tensor([4., 4., 4., 4., 4.])
[4. 4. 4. 4. 4.]


In [97]:
a = np.ones(5)
print(a)
# from numpy to tensor
b = torch.from_numpy(a)
print(type(b))
print(b)

[1. 1. 1. 1. 1.]
<class 'torch.Tensor'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [101]:
# Careful!
# if both a and b are in the GPU, 
# both objects will share the same memory location
# both objects will be modified
a+=1
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### Move objects from cpu to gpu and viceversa

In [104]:

if torch.cuda.is_available():
    device = torch.device('cuda')
    # create tensor on gpu
    x = torch.ones(5, device=device)
    # create tensor on cpu and then move to gpu
    y = torch.ones(5)
    y = y.to(device)
    # make the operation on gpu
    z = x + y
    # z.numpy() # produce and error because numpy can only handle cpu tensor  
    # move back to cpu
    z = z.to('cpu')

print(x)
print(y)
print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([2., 2., 2., 2., 2.])


### Requires grads

In [107]:
# requires_grad say that it will be optimized
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
