## Calculate gradients

In [1]:
import torch

## Gradient Function

In [2]:
x = torch.randn(3,requires_grad=True)
print(x)

tensor([-1.6403, -1.6034,  0.2060], requires_grad=True)


In [3]:
#since the operation is add a number the grad_fn will be AddBackward
y=x+2
y

tensor([0.3597, 0.3966, 2.2060], grad_fn=<AddBackward0>)

In [4]:
#since the operation is add a number the grad_fn will be SubBackward
y=x-2
y

tensor([-3.6403, -3.6034, -1.7940], grad_fn=<SubBackward0>)

In [5]:
#since the operation is add a number the grad_fn will be MultBackward
y=x*2
y

tensor([-3.2806, -3.2067,  0.4120], grad_fn=<MulBackward0>)

In [6]:
#since the operation is add a number the grad_fn will be divBackward
y=x/2
y

tensor([-0.8202, -0.8017,  0.1030], grad_fn=<DivBackward0>)

## Gradient Calculation

<img src="backpropagation.png" width="500">

In [7]:
x = torch.randn(3,requires_grad=True)
print(x)

tensor([ 0.3043, -0.0707,  1.7609], requires_grad=True)


In [8]:
y=x+2
print("y ",y)
z=y*y*2
#z=z.mean()
print(z)

y  tensor([2.3043, 1.9293, 3.7609], grad_fn=<AddBackward0>)
tensor([10.6194,  7.4441, 28.2884], grad_fn=<MulBackward0>)


In [9]:
# z is not an scalar (z.mean()) we must give the vector v
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v) #dz/dx
print(x.grad)

tensor([0.9217, 7.7170, 0.0150])


**Jacobian Chain Rule**

<img src="jacobian_matrix.png" width="500">

## Preventing Gradient History

In [14]:
# first option
x = torch.randn(3,requires_grad=True)
x.requires_grad_(False)
print(x)

tensor([ 0.9287,  0.8132, -0.2667])


In [16]:
# secod option
x = torch.randn(3,requires_grad=True)
y = x.detach()
print(x)
print(y)

tensor([ 0.2979, -0.1819, -0.6232], requires_grad=True)
tensor([ 0.2979, -0.1819, -0.6232])


In [19]:
# third option
with torch.no_grad():
    x = torch.randn(3,requires_grad=True)
    y = x + 2
print(x)
print(y)

tensor([-0.4981,  1.9292,  0.5857], requires_grad=True)
tensor([1.5019, 3.9292, 2.5857])


## Training Example

In [25]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)

    # before next optimization we must  empty the gradient
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [29]:
weights = torch.ones(4, requires_grad=True)

# define Optimizer
# optimizer = torch.optim.SGD(weights, lr=0.01)
# optimizer.step()
# optimizer.zero_grad()